language: node_js
node_js:
  - "0.10"

after_success:
  - npm run cover-publish
addons:
  code_climate:
    repo_token:
      # # get your token from https://codeclimate.com/github/benjamine/fiberglass
      # gem install travis
      # travis encrypt <projecttoken>
      secure: "project's encrypted token"
